sonar.projectName=e-commerce
sonar.sourceEncoding=UTF-8
sonar.sources=1-apps,.github/workflows
sonar.exclusions=**/.git/**,**/.venv/**,**/__pycache__/**,**/.pytest_cache/**,**/static/products/**,**/*.jpg,**/*.jpeg,**/*.png,**/*.gif,**/*.docx
