---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: prod-ecommerce
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ecommerce:password@postgres-service.prod-ecommerce:5432/ecommerce"
  SECRET_KEY: "your-secret-key"
