apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ecommerce
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: ecommerce
  labels:
    app: application
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: application

---
apiVersion: v1
kind: Service
metadata:
  name: presentation
  namespace: ecommerce
  labels:
    app: presentation
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: presentation
